name: Create jira issue from github issue

on:
  issues:
    types: [opened]

jobs:
  update_jira:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: SWTEAM
        issuetype: Task
        summary: |
          Build completed for ${{ github.repository }}

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
